name: "build"
on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

permissions:
  contents: write

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "Tencent/ncnn"
          latest: true
          fileName: "ncnn-*-windows-vs2022.zip"

      - name: Unzip
        shell: bash
        run: |
          unzip ncnn-*-windows-vs2022.zip -d ./native/ncnn
          ls -l ./native/ncnn

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "Tencent/ncnn"
          latest: true
          fileName: "ncnn-*-ubuntu-2204.zip"

      - name: Unzip
        shell: bash
        run: |
          unzip ncnn-*-ubuntu-2204.zip -d ./native/ncnn
          ls -l ./native/ncnn

  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "Tencent/ncnn"
          latest: true
          fileName: "ncnn-*-android-vulkan.zip"

      - name: Unzip
        shell: bash
        run: |
          unzip ncnn-*-android-vulkan.zip -d ./native/ncnn
          ls -l ./native/ncnn

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r25b

      - name: Build aarch64 ncnn
        shell: bash
        working-directory: ./native/ncnn
        run: |
          mkdir -p build-android-aarch64
          cd build-android-aarch64
          cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI="arm64-v8a" \
            -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON
          make -j$(nproc)
          make install

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "Tencent/ncnn"
          latest: true
          fileName: "ncnn-*-macos-vulkan.zip"

      - name: Unzip
        shell: bash
        run: |
          unzip ncnn-*-macos-vulkan.zip -d ./native/ncnn
          ls -l ./native/ncnn